### ISSUE TITLE
Linking Directly to Answer Does Not Show Answer

### ISSUE THREAD

**Issue by owenkellogg** [pow-co/next.askbitcoin.ai#12]
For example: https://next.askbitcoin.ai/answers/8b8cba9f665c19960c527c4ce25edc326d98b145f97a7614b93fcaaa98a6c13b

**Comment by GuiDeMa** [comment]
#7 already exists. I've been trying to fix this for days! any idea of what's wrong ?

**Comment by owenkellogg** [comment]
Is this issue complete?

**Comment by owenkellogg** [comment]
Complete
