### ISSUE TITLE
Moble site: problem with accidentally boosting while scrolling right-handed

### ISSUE THREAD

**Issue by DanielKrawisz** [pow-co/next.askbitcoin.ai#14]

**Comment by GuiDeMa** [comment]
What would you suggest ?

**Comment by eddiewillers** [comment]
Wouldn't it be easier to move your thumb?

The button has to be somewhere.

Wherever that is could result in an accidental tap when scrolling on mobile.

Unless maybe the boost button was dead center.

**Comment by GuiDeMa** [comment]
Tell me how you find it now I tried to move buttons to the left should be better

**Comment by eddiewillers** [comment]
Really good! You left a whole lane for right thumb scrolling! @DanielKrawisz do you agree this issue is closed?
