### ISSUE TITLE
No boost is shown for questions on question page. 

### ISSUE THREAD

**Issue by DanielKrawisz** [pow-co/next.askbitcoin.ai#17]
Example: https://next.askbitcoin.ai/questions/26b2d4ee31e2d6cd5f815af04c5190ad56578588dd7802f9a9230151681acfd5 

The question shows 2.6 diff for me (since last week) on the main page but on its own page shows zero.

**Comment by eddiewillers** [comment]
This is the same issue as this one :

https://github.com/pow-co/askbitcoin/issues/63

And this one:

https://github.com/pow-co/askbitcoin/issues/76

And these are the top boosted issues on Powco.dev

I therefore stake 100 POWCO on the completion of fixing this issue completely: Fixing the API and then making the results appear with the correct difficulty on the Question page.

Care to join me?

@DanielKrawisz 
@GuiDeMa 
@owenkellogg 
@vamosvigilante 

🥇

**Comment by owenkellogg** [comment]
@eddiewillers please send 100 pow.co tokens to owenkellog@relayx.io as this issue is resolved :D

**Comment by eddiewillers** [comment]
> @eddiewillers please send 100 pow.co tokens to owenkellog@relayx.io as this issue is resolved :D

Two Gs in Kellogg.

💯🥇
